services:
  # MongoDB Database
  mongodb:
    image: mongo:4.4
    container_name: attendance-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: attender
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - attendance-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://host.docker.internal:27017/attender
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - attendance-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: attendance-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - attendance-network

# Named volumes
volumes:
  mongodb_data:

# Networks
networks:
  attendance-network:
    driver: bridge
