global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:3000']
